local home = os.getenv("HOME")

hl.env("EDITOR", "helix")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("WALLPAPER_DIR", home .. "/.config/assets/media")
hl.env("HYPRLAND_DEFAULT_WALLPAPER", home .. "/.config/assets/media/anim/bg_dark_anim_0_08.gif")
hl.env("SCREENSHOT_DIR", home .. "/Pictures/Screenshots")
hl.env("HYPRCURSOR_THEME", "rose-pine-hyprcursor")
hl.env("HYPRCURSOR_SIZE", "32")
hl.env("XCURSOR_THEME", "rose-pine-hyprcursor")
hl.env("XCURSOR_SIZE", "32")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "1")
hl.env("QT_QPA_PLATFORM", "wayland")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("XDG_CONFIG_HOME", home .. "/.config")
hl.env("XDG_CACHE_HOME", home .. "/.cache")
hl.env("XDG_DATA_HOME", home .. "/.local/share")
hl.env("_JAVA_AWT_WM_NONREPARENTING", "1")
